# Generated by Django 6.0.3 on 2026-03-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documenttype_is_global_tenant_client_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.tenant'),
        ),
    ]
