# Generated by Django 6.0.3 on 2026-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tenant_total_docs_generated_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
    ]
